//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopProduct()
        {
            this.ShopOrderItems = new HashSet<ShopOrderItem>();
        }
    
        public int product_ID { get; set; }
        public string product_Type { get; set; }
        public string product_Name { get; set; }
        public string product_Detail { get; set; }
        public Nullable<int> product_All { get; set; }
        public Nullable<int> product_Remain { get; set; }
        public Nullable<decimal> product_Price { get; set; }
        public Nullable<decimal> product_Discount { get; set; }
        public string product_IMG { get; set; }
        public Nullable<int> product_Serial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderItem> ShopOrderItems { get; set; }
    }
}
