//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopType
    {
        public int type_ID { get; set; }
        public string type_Name { get; set; }
        public Nullable<int> type_Serial { get; set; }
    }
}
