//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopOrder()
        {
            this.ShopOrderItems = new HashSet<ShopOrderItem>();
        }
    
        public int order_ID { get; set; }
        public Nullable<int> customer_ID { get; set; }
        public Nullable<int> customer_Serial { get; set; }
        public Nullable<System.DateTime> order_DATE { get; set; }
        public Nullable<System.DateTime> order_NOW { get; set; }
        public Nullable<decimal> order_Total { get; set; }
        public Nullable<int> order_Serial { get; set; }
    
        public virtual ShopCustomer ShopCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrderItem> ShopOrderItems { get; set; }
    }
}
