//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopSale
    {
        public int sale_ID { get; set; }
        public Nullable<int> product_ID1 { get; set; }
        public Nullable<int> product_ID2 { get; set; }
    }
}
