//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopOrderItem
    {
        public int orderItem_ID { get; set; }
        public Nullable<int> order_ID { get; set; }
        public Nullable<int> product_ID { get; set; }
        public string orderItem_Name { get; set; }
        public Nullable<int> orderItem_Amount { get; set; }
        public Nullable<decimal> orderItem_Price { get; set; }
        public Nullable<decimal> orderItem_Total { get; set; }
        public Nullable<decimal> orderItem_Discount { get; set; }
        public Nullable<int> customer_Serial { get; set; }
        public Nullable<int> orderItem_Serial { get; set; }
    
        public virtual ShopOrder ShopOrder { get; set; }
        public virtual ShopProduct ShopProduct { get; set; }
    }
}
