//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopEmployee()
        {
            this.ShopCustomers = new HashSet<ShopCustomer>();
        }
    
        public int employee_ID { get; set; }
        public string employee_Fname { get; set; }
        public string employee_Lname { get; set; }
        public string employee_Address { get; set; }
        public Nullable<int> employee_TEL { get; set; }
        public string employee_Username { get; set; }
        public string employee_Password { get; set; }
        public Nullable<int> employee_Serial { get; set; }
        public Nullable<int> employee_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopCustomer> ShopCustomers { get; set; }
    }
}
