//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMSU_PRO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShopCustomer()
        {
            this.ShopOrders = new HashSet<ShopOrder>();
        }
    
        public int customer_ID { get; set; }
        public string customer_Fname { get; set; }
        public string customer_Lname { get; set; }
        public string customer_Address { get; set; }
        public Nullable<int> customer_TEL { get; set; }
        public Nullable<int> employee_ID { get; set; }
        public string customer_Username { get; set; }
        public string customer_Password { get; set; }
        public Nullable<int> customer_Serial { get; set; }
        public Nullable<int> orderitem_ID { get; set; }
    
        public virtual ShopEmployee ShopEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopOrder> ShopOrders { get; set; }
    }
}
